# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://andy6804tw.github.io/
date_format: "ordinal"
title: 1010Code
subtitle: "10's Blog"
description: "10的個人部落格"
keywords: 10, 1010Code
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Tsai Yi Lin
organization: 1010 Code Workshop
organization_url: https://1010code.blogspot.tw/
github_username: andy6804tw
location: Taiwan, Tainan
email: andy6804tw@yahoo.com.tw

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首頁

  -
    href: /categories/
    label: 分類

  -
    href: /wiki/
    label: 電子書

  -
    href: /links/
    label: 連結

  -
    href: /about/
    label: 關於

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: andy6804tw/andy6804tw.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: disqus
# ！重要！請修改下面這些信息為你自己申請的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: andy6804tw-github-io
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: andy6804tw
    repo: blog-comments
    oauth:
        client_id: c03f944213b41794672c
        client_secret: 7372a544b838d11cf3e4b3d935378d7d46956c39
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: andy6804tw
    repo: blog-comments
    clientID: c03f944213b41794672c
    clientSecret: 7372a544b838d11cf3e4b3d935378d7d46956c39
# 在使用其它評論組件時可點擊顯示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-XRN47TB6Z8
